# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Install composer packages
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
